import type { ProtectedRoute } from "../types.js";

export const AUTH_HR_ROUTES: ProtectedRoute[] = [
  {
    method: "GET",
    pattern: /^\/auth\/context\/tenants$/,
    actionKey: "auth.context.tenants.list",
  },
  {
    method: "POST",
    pattern: /^\/auth\/context\/tenant\/select$/,
    actionKey: "auth.context.tenant.select",
    tenantSource: "body.tenantId",
  },
  {
    method: "GET",
    pattern: /^\/auth\/context\/branches$/,
    actionKey: "auth.context.branches.list",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/auth\/context\/branch\/select$/,
    actionKey: "auth.context.branch.select",
    tenantSource: "token",
    branchSource: "body.branchId",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/invite$/,
    actionKey: "org.membership.invite",
    tenantSource: "body.tenantId",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/invite$/,
    actionKey: "org.membership.invite",
    tenantSource: "body.tenantId",
  },
  {
    method: "GET",
    pattern: /^\/auth\/memberships\/invitations$/,
    actionKey: "org.membership.invitations.list",
  },
  {
    method: "GET",
    pattern: /^\/org\/memberships\/invitations$/,
    actionKey: "org.membership.invitations.list",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/invitations\/[^/]+\/accept$/,
    actionKey: "org.membership.invitation.accept",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/invitations\/[^/]+\/accept$/,
    actionKey: "org.membership.invitation.accept",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/invitations\/[^/]+\/reject$/,
    actionKey: "org.membership.invitation.revoke",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/invitations\/[^/]+\/reject$/,
    actionKey: "org.membership.invitation.revoke",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/[^/]+\/role$/,
    actionKey: "org.membership.role.change",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/[^/]+\/role$/,
    actionKey: "org.membership.role.change",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/[^/]+\/revoke$/,
    actionKey: "org.membership.revoke",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/[^/]+\/revoke$/,
    actionKey: "org.membership.revoke",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/[^/]+\/branches$/,
    actionKey: "hr.staff.branch.assign",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/hr\/staff\/memberships\/[^/]+\/branches$/,
    actionKey: "hr.staff.branch.assign",
    tenantSource: "path.membershipId",
  },
  {
    method: "GET",
    pattern: /^\/hr\/staff$/,
    actionKey: "hr.staff.list",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/staff\/memberships\/[^/]+\/branches$/,
    actionKey: "hr.staff.branch.list",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/staff\/[^/]+$/,
    actionKey: "hr.staff.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/shifts\/schedule$/,
    actionKey: "hr.shift.schedule.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/shifts\/me$/,
    actionKey: "hr.shift.schedule.readSelf",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/shifts\/memberships\/[^/]+$/,
    actionKey: "hr.shift.schedule.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/shifts\/instances\/[^/]+$/,
    actionKey: "hr.shift.schedule.read",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/patterns$/,
    actionKey: "hr.shift.pattern.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/hr\/shifts\/patterns\/[^/]+$/,
    actionKey: "hr.shift.pattern.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/patterns\/[^/]+\/deactivate$/,
    actionKey: "hr.shift.pattern.deactivate",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/instances$/,
    actionKey: "hr.shift.instance.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/hr\/shifts\/instances\/[^/]+$/,
    actionKey: "hr.shift.instance.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/instances\/[^/]+\/cancel$/,
    actionKey: "hr.shift.instance.cancel",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/auth\/tenants$/,
    actionKey: "org.tenant.provision",
  },
  {
    method: "POST",
    pattern: /^\/org\/tenants$/,
    actionKey: "org.tenant.provision",
  },
  {
    method: "POST",
    pattern: /^\/attendance\/check-in$/,
    actionKey: "attendance.checkIn",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/attendance\/check-out$/,
    actionKey: "attendance.checkOut",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/attendance\/me$/,
    actionKey: "attendance.listMine",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/attendance\/force-end$/,
    actionKey: "attendance.forceEnd",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/attendance\/branch$/,
    actionKey: "attendance.listBranch",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/attendance\/tenant$/,
    actionKey: "attendance.listTenant",
    tenantSource: "token",
  },
];
