import type { ProtectedRoute } from "../types.js";

export const CASH_ORDER_SALE_RECEIPT_ROUTES: ProtectedRoute[] = [
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/active$/,
    actionKey: "cashSession.active.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions$/,
    actionKey: "cashSession.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+$/,
    actionKey: "cashSession.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+\/sales$/,
    actionKey: "cashSession.sales.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+\/movements$/,
    actionKey: "cashSession.movements.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+\/x$/,
    actionKey: "cashSession.x.view",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+\/z$/,
    actionKey: "cashSession.z.view",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions$/,
    actionKey: "cashSession.open",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/close$/,
    actionKey: "cashSession.close",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/force-close$/,
    actionKey: "cashSession.forceClose",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/movements\/paid-in$/,
    actionKey: "cashSession.movement.paidIn",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/movements\/paid-out$/,
    actionKey: "cashSession.movement.paidOut",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/movements\/adjustment$/,
    actionKey: "cashSession.movement.adjustment",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/checkout\/cash\/finalize$/,
    actionKey: "checkout.cash.finalize",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/checkout\/khqr\/initiate$/,
    actionKey: "checkout.khqr.initiate",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/checkout\/khqr\/intents\/[^/]+$/,
    actionKey: "checkout.khqr.intent.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/checkout\/khqr\/intents\/[^/]+\/cancel$/,
    actionKey: "checkout.khqr.intent.cancel",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/orders$/,
    actionKey: "order.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/orders\/[^/]+$/,
    actionKey: "order.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders$/,
    actionKey: "order.place",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders\/[^/]+\/cancel$/,
    actionKey: "order.cancel",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders\/[^/]+\/items$/,
    actionKey: "order.items.add",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders\/[^/]+\/checkout$/,
    actionKey: "order.checkout",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/orders\/[^/]+\/fulfillment$/,
    actionKey: "order.fulfillment.status.update",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sales$/,
    actionKey: "sale.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sales\/[^/]+$/,
    actionKey: "sale.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/finalize$/,
    actionKey: "sale.finalize",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/request$/,
    actionKey: "sale.void.request",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/approve$/,
    actionKey: "sale.void.approve",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/reject$/,
    actionKey: "sale.void.reject",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/execute$/,
    actionKey: "sale.void.execute",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sales\/[^/]+\/void-request$/,
    actionKey: "sale.void.request.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/receipts\/sales\/[^/]+$/,
    actionKey: "receipt.readBySale",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/receipts\/[^/]+$/,
    actionKey: "receipt.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/receipts\/[^/]+\/print$/,
    actionKey: "receipt.print",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/receipts\/[^/]+\/reprint$/,
    actionKey: "receipt.reprint",
    tenantSource: "token",
    branchSource: "token",
  },
];
