import type { ProtectedRoute } from "../types.js";

export const MENU_MEDIA_PAYMENT_ROUTES: ProtectedRoute[] = [
  {
    method: "GET",
    pattern: /^\/menu\/items$/,
    actionKey: "menu.items.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/images\/upload$/,
    actionKey: "menu.images.upload",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/media\/images\/upload$/,
    actionKey: "media.images.upload",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/sales\/[^/]+\/generate$/,
    actionKey: "payment.khqr.generate",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/attempts$/,
    actionKey: "payment.khqr.attempt.register",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/attempts\/[^/]+\/cancel$/,
    actionKey: "payment.khqr.attempt.cancel",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/payments\/khqr\/attempts\/by-md5\/[^/]+$/,
    actionKey: "payment.khqr.attempt.readByMd5",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/payments\/khqr\/attempts\/[^/]+$/,
    actionKey: "payment.khqr.attempt.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/confirm$/,
    actionKey: "payment.khqr.confirm",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/items\/all$/,
    actionKey: "menu.items.listAll",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/items\/[^/]+$/,
    actionKey: "menu.items.read",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items$/,
    actionKey: "menu.items.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/items\/[^/]+$/,
    actionKey: "menu.items.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items\/[^/]+\/archive$/,
    actionKey: "menu.items.archive",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items\/[^/]+\/restore$/,
    actionKey: "menu.items.restore",
    tenantSource: "token",
  },
  {
    method: "PUT",
    pattern: /^\/menu\/items\/[^/]+\/visibility$/,
    actionKey: "menu.items.visibility.set",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/categories$/,
    actionKey: "menu.categories.list",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/categories$/,
    actionKey: "menu.categories.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/categories\/[^/]+$/,
    actionKey: "menu.categories.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/categories\/[^/]+\/archive$/,
    actionKey: "menu.categories.archive",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/modifier-groups$/,
    actionKey: "menu.modifierGroups.list",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups$/,
    actionKey: "menu.modifierGroups.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/modifier-groups\/[^/]+$/,
    actionKey: "menu.modifierGroups.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/archive$/,
    actionKey: "menu.modifierGroups.archive",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options$/,
    actionKey: "menu.modifierOptions.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options\/[^/]+$/,
    actionKey: "menu.modifierOptions.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options\/[^/]+\/archive$/,
    actionKey: "menu.modifierOptions.archive",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options\/[^/]+\/restore$/,
    actionKey: "menu.modifierOptions.restore",
    tenantSource: "token",
  },
  {
    method: "PUT",
    pattern: /^\/menu\/items\/[^/]+\/composition$/,
    actionKey: "menu.composition.upsert",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items\/[^/]+\/composition\/evaluate$/,
    actionKey: "menu.composition.evaluate",
    tenantSource: "token",
  },
];
