import type { ProtectedRoute } from "../types.js";

export const REPORTS_NOTIFICATION_SYNC_ROUTES: ProtectedRoute[] = [
  {
    method: "GET",
    pattern: /^\/reports\/sales\/summary$/,
    actionKey: "reports.sales.summary",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/reports\/sales\/drill-down$/,
    actionKey: "reports.sales.drillDown",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/reports\/restock-spend\/summary$/,
    actionKey: "reports.restockSpend.summary",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/reports\/restock-spend\/drill-down$/,
    actionKey: "reports.restockSpend.drillDown",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/reports\/attendance\/summary$/,
    actionKey: "reports.attendance.summary",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/reports\/attendance\/drill-down$/,
    actionKey: "reports.attendance.drillDown",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/inbox$/,
    actionKey: "operationalNotification.inbox.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/unread-count$/,
    actionKey: "operationalNotification.inbox.unreadCount",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/stream$/,
    actionKey: "operationalNotification.inbox.stream",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/[^/]+$/,
    actionKey: "operationalNotification.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/notifications\/[^/]+\/read$/,
    actionKey: "operationalNotification.read.mark",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/notifications\/read-all$/,
    actionKey: "operationalNotification.read.markAll",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sync\/replay$/,
    actionKey: "pushSync.apply",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sync\/push$/,
    actionKey: "pushSync.apply",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sync\/replay\/batches\/[^/]+$/,
    actionKey: "pushSync.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sync\/push\/batches\/[^/]+$/,
    actionKey: "pushSync.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sync\/pull$/,
    actionKey: "pullSync.pull",
    tenantSource: "token",
    branchSource: "token",
  },
];
