import type { ActionMetadata } from "./types.js";

export const ACTION_METADATA: Record<string, ActionMetadata> = {
  "auth.context.tenants.list": { scope: "GLOBAL", effect: "READ" },
  "auth.context.tenant.select": { scope: "TENANT", effect: "READ" },
  "auth.context.branches.list": { scope: "TENANT", effect: "READ" },
  "auth.context.branch.select": { scope: "BRANCH", effect: "READ" },
  "org.membership.invite": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.membership.invitations.list": { scope: "GLOBAL", effect: "READ" },
  "org.membership.invitation.accept": { scope: "GLOBAL", effect: "WRITE" },
  "org.membership.invitation.revoke": { scope: "GLOBAL", effect: "WRITE" },
  "org.membership.role.change": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.membership.revoke": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "hr.staff.branch.assign": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "hr.staff.list": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.staff.read": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.staff.branch.list": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.pattern.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.pattern.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.pattern.deactivate": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.instance.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.instance.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.instance.cancel": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.schedule.read": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
  },
  "hr.shift.schedule.readSelf": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER", "CLERK"],
  },
  "org.tenant.provision": { scope: "GLOBAL", effect: "WRITE" },
  "tenant.provision": { scope: "GLOBAL", effect: "WRITE" }, // compatibility alias
  "attendance.checkIn": {
    scope: "BRANCH",
    effect: "WRITE",
    entitlementKey: "module.workforce",
  },
  "attendance.checkOut": {
    scope: "BRANCH",
    effect: "WRITE",
    entitlementKey: "module.workforce",
  },
  "attendance.listMine": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "module.workforce",
  },
  "attendance.forceEnd": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.workforce",
  },
  "attendance.listBranch": {
    scope: "BRANCH",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.workforce",
  },
  "attendance.listTenant": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.workforce",
  },
  "org.tenant.current.read": { scope: "TENANT", effect: "READ" },
  "org.branches.accessible.read": { scope: "TENANT", effect: "READ" },
  "org.branch.current.read": { scope: "BRANCH", effect: "READ" },
  "org.branch.current.profile.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.branch.profile.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.branch.current.khqrReceiver.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "core.pos",
  },
  "org.branch.current.attendanceLocation.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.branch.activation.initiate": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.branch.activation.confirm": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "subscription.state.current.read": { scope: "TENANT", effect: "READ" },
  "subscription.entitlements.currentBranch.read": {
    scope: "BRANCH",
    effect: "READ",
  },
  "audit.view": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "policy.currentBranch.read": {
    scope: "BRANCH",
    effect: "READ",
  },
  "policy.currentBranch.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "menu.items.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.images.upload": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "media.images.upload": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
  },
  "payment.khqr.attempt.register": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "payment.khqr.attempt.cancel": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "payment.khqr.generate": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "payment.khqr.attempt.read": {
    scope: "BRANCH",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "payment.khqr.attempt.readByMd5": {
    scope: "BRANCH",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "payment.khqr.confirm": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "menu.items.listAll": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.read": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.items.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.restore": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.visibility.set": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.categories.list": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.categories.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.categories.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.categories.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.list": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierOptions.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierOptions.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierOptions.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierOptions.restore": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.composition.upsert": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.itemModifierOptionEffects.replace": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.composition.evaluate": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "discount.rules.list": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "discount.rules.read": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "discount.rules.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "core.pos",
  },
  "discount.rules.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "core.pos",
  },
  "discount.rules.activate": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "core.pos",
  },
  "discount.rules.deactivate": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "core.pos",
  },
  "discount.rules.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "core.pos",
  },
  "discount.rules.preflight.eligibleItems": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "core.pos",
  },
  "discount.eligibility.resolve": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "inventory.categories.list": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.categories.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.categories.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.categories.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.items.list": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.items.read": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.items.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.items.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.items.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.items.restore": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.restockBatches.list": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.restockBatches.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.restockBatches.updateMeta": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.restockBatches.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.adjustments.apply": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
    entitlementKey: "module.inventory",
  },
  "inventory.journal.list": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.journal.listAll": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.stock.branch.read": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "inventory.stock.aggregate.read": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "module.inventory",
  },
  "cashSession.open": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "cashSession.close": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "cashSession.forceClose": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "cashSession.paidIn": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "cashSession.paidOut": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "cashSession.adjust": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "cashSession.movement.paidIn": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "cashSession.movement.paidOut": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "cashSession.movement.adjustment": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "cashSession.active.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "cashSession.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "cashSession.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "cashSession.sales.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "cashSession.movements.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "cashSession.x.view": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "cashSession.z.view": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "checkout.cash.finalize": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "checkout.khqr.initiate": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "checkout.khqr.intent.read": {
    scope: "BRANCH",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "checkout.khqr.intent.cancel": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.place": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.cancel": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.items.add": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.checkout": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.manualPaymentClaim.list": {
    scope: "BRANCH",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.manualPaymentClaim.create": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.manualPaymentClaim.approve": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "order.manualPaymentClaim.reject": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "order.fulfillment.status.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "order.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "order.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "sale.finalize": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "sale.void.request": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "sale.void.approve": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "sale.void.reject": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "sale.void.execute": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "sale.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "sale.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "sale.void.request.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "receipt.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "receipt.readBySale": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "receipt.print": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER", "CASHIER"],
    entitlementKey: "core.pos",
  },
  "receipt.reprint": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "reports.sales.summary": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "reports.sales.drillDown": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "reports.restockSpend.summary": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "reports.restockSpend.drillDown": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "reports.attendance.summary": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "reports.attendance.drillDown": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "operationalNotification.inbox.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "operationalNotification.inbox.stream": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "operationalNotification.inbox.unreadCount": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "operationalNotification.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "operationalNotification.read.mark": {
    scope: "BRANCH",
    effect: "WRITE",
    entitlementKey: "core.pos",
  },
  "operationalNotification.read.markAll": {
    scope: "BRANCH",
    effect: "WRITE",
    entitlementKey: "core.pos",
  },
  "pushSync.apply": {
    scope: "BRANCH",
    effect: "WRITE",
    entitlementKey: "core.pos",
  },
  "pushSync.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "pullSync.pull": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
};
