import type { ActionMetadata } from "./types.js";

export const ACTION_METADATA: Record<string, ActionMetadata> = {
  "auth.context.tenants.list": { scope: "GLOBAL", effect: "READ" },
  "auth.context.tenant.select": { scope: "TENANT", effect: "READ" },
  "auth.context.branches.list": { scope: "TENANT", effect: "READ" },
  "auth.context.branch.select": { scope: "BRANCH", effect: "READ" },
  "org.membership.invite": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.membership.invitations.list": { scope: "GLOBAL", effect: "READ" },
  "org.membership.invitation.accept": { scope: "GLOBAL", effect: "WRITE" },
  "org.membership.invitation.reject": { scope: "GLOBAL", effect: "WRITE" },
  "org.membership.role.change": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.membership.revoke": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "hr.staff.branch.assign": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.tenant.provision": { scope: "GLOBAL", effect: "WRITE" },
  "tenant.provision": { scope: "GLOBAL", effect: "WRITE" }, // compatibility alias
  "attendance.checkIn": {
    scope: "BRANCH",
    effect: "WRITE",
    entitlementKey: "module.workforce",
  },
  "attendance.checkOut": {
    scope: "BRANCH",
    effect: "WRITE",
    entitlementKey: "module.workforce",
  },
  "attendance.listMine": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "module.workforce",
  },
  "org.tenant.current.read": { scope: "TENANT", effect: "READ" },
  "org.branches.accessible.read": { scope: "TENANT", effect: "READ" },
  "org.branch.current.read": { scope: "BRANCH", effect: "READ" },
  "org.branch.firstActivation.initiate": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "org.branch.firstActivation.confirm": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "subscription.state.current.read": { scope: "TENANT", effect: "READ" },
  "subscription.entitlements.currentBranch.read": {
    scope: "BRANCH",
    effect: "READ",
  },
  "audit.view": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "policy.currentBranch.read": {
    scope: "BRANCH",
    effect: "READ",
  },
  "policy.currentBranch.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN"],
  },
  "menu.items.list": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.items.listAll": {
    scope: "TENANT",
    effect: "READ",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.read": {
    scope: "BRANCH",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.items.create": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.update": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.archive": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.restore": {
    scope: "BRANCH",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.items.visibility.set": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.categories.list": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.categories.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.categories.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.categories.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.list": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierGroups.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierOptions.create": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierOptions.update": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.modifierOptions.archive": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.composition.upsert": {
    scope: "TENANT",
    effect: "WRITE",
    allowedRoles: ["OWNER", "ADMIN", "MANAGER"],
    entitlementKey: "core.pos",
  },
  "menu.composition.evaluate": {
    scope: "TENANT",
    effect: "READ",
    entitlementKey: "core.pos",
  },
};
