import type { ProtectedRoute } from "./types.js";

export const PROTECTED_ROUTES: ProtectedRoute[] = [
  {
    method: "GET",
    pattern: /^\/auth\/context\/tenants$/,
    actionKey: "auth.context.tenants.list",
  },
  {
    method: "POST",
    pattern: /^\/auth\/context\/tenant\/select$/,
    actionKey: "auth.context.tenant.select",
    tenantSource: "body.tenantId",
  },
  {
    method: "GET",
    pattern: /^\/auth\/context\/branches$/,
    actionKey: "auth.context.branches.list",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/auth\/context\/branch\/select$/,
    actionKey: "auth.context.branch.select",
    tenantSource: "token",
    branchSource: "body.branchId",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/invite$/,
    actionKey: "org.membership.invite",
    tenantSource: "body.tenantId",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/invite$/,
    actionKey: "org.membership.invite",
    tenantSource: "body.tenantId",
  },
  {
    method: "GET",
    pattern: /^\/auth\/memberships\/invitations$/,
    actionKey: "org.membership.invitations.list",
  },
  {
    method: "GET",
    pattern: /^\/org\/memberships\/invitations$/,
    actionKey: "org.membership.invitations.list",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/invitations\/[^/]+\/accept$/,
    actionKey: "org.membership.invitation.accept",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/invitations\/[^/]+\/accept$/,
    actionKey: "org.membership.invitation.accept",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/invitations\/[^/]+\/reject$/,
    actionKey: "org.membership.invitation.revoke",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/invitations\/[^/]+\/reject$/,
    actionKey: "org.membership.invitation.revoke",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/[^/]+\/role$/,
    actionKey: "org.membership.role.change",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/[^/]+\/role$/,
    actionKey: "org.membership.role.change",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/[^/]+\/revoke$/,
    actionKey: "org.membership.revoke",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/org\/memberships\/[^/]+\/revoke$/,
    actionKey: "org.membership.revoke",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/auth\/memberships\/[^/]+\/branches$/,
    actionKey: "hr.staff.branch.assign",
    tenantSource: "path.membershipId",
  },
  {
    method: "POST",
    pattern: /^\/hr\/staff\/memberships\/[^/]+\/branches$/,
    actionKey: "hr.staff.branch.assign",
    tenantSource: "path.membershipId",
  },
  {
    method: "GET",
    pattern: /^\/hr\/staff$/,
    actionKey: "hr.staff.list",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/staff\/memberships\/[^/]+\/branches$/,
    actionKey: "hr.staff.branch.list",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/staff\/[^/]+$/,
    actionKey: "hr.staff.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/shifts\/schedule$/,
    actionKey: "hr.shift.schedule.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/shifts\/memberships\/[^/]+$/,
    actionKey: "hr.shift.schedule.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/hr\/shifts\/instances\/[^/]+$/,
    actionKey: "hr.shift.schedule.read",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/patterns$/,
    actionKey: "hr.shift.pattern.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/hr\/shifts\/patterns\/[^/]+$/,
    actionKey: "hr.shift.pattern.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/patterns\/[^/]+\/deactivate$/,
    actionKey: "hr.shift.pattern.deactivate",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/instances$/,
    actionKey: "hr.shift.instance.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/hr\/shifts\/instances\/[^/]+$/,
    actionKey: "hr.shift.instance.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/hr\/shifts\/instances\/[^/]+\/cancel$/,
    actionKey: "hr.shift.instance.cancel",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/auth\/tenants$/,
    actionKey: "org.tenant.provision",
  },
  {
    method: "POST",
    pattern: /^\/org\/tenants$/,
    actionKey: "org.tenant.provision",
  },
  {
    method: "POST",
    pattern: /^\/attendance\/check-in$/,
    actionKey: "attendance.checkIn",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/attendance\/check-out$/,
    actionKey: "attendance.checkOut",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/attendance\/me$/,
    actionKey: "attendance.listMine",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/attendance\/force-end$/,
    actionKey: "attendance.forceEnd",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/attendance\/branch$/,
    actionKey: "attendance.listBranch",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/attendance\/tenant$/,
    actionKey: "attendance.listTenant",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/org\/tenant\/current$/,
    actionKey: "org.tenant.current.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/org\/branches\/accessible$/,
    actionKey: "org.branches.accessible.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/org\/branch\/current$/,
    actionKey: "org.branch.current.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/org\/branch\/current\/khqr-receiver$/,
    actionKey: "org.branch.current.khqrReceiver.update",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/org\/branch\/current\/attendance-location$/,
    actionKey: "org.branch.current.attendanceLocation.update",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/org\/branches\/activation\/initiate\/?$/,
    actionKey: "org.branch.activation.initiate",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/org\/branches\/activation\/confirm\/?$/,
    actionKey: "org.branch.activation.confirm",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/subscription\/state\/current$/,
    actionKey: "subscription.state.current.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/subscription\/entitlements\/current-branch$/,
    actionKey: "subscription.entitlements.currentBranch.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/audit\/events$/,
    actionKey: "audit.view",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/policy\/current-branch$/,
    actionKey: "policy.currentBranch.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/policy\/current-branch$/,
    actionKey: "policy.currentBranch.update",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/items$/,
    actionKey: "menu.items.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/images\/upload$/,
    actionKey: "menu.images.upload",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/media\/images\/upload$/,
    actionKey: "media.images.upload",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/sales\/[^/]+\/generate$/,
    actionKey: "payment.khqr.generate",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/attempts$/,
    actionKey: "payment.khqr.attempt.register",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/attempts\/[^/]+\/cancel$/,
    actionKey: "payment.khqr.attempt.cancel",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/payments\/khqr\/attempts\/by-md5\/[^/]+$/,
    actionKey: "payment.khqr.attempt.readByMd5",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/payments\/khqr\/attempts\/[^/]+$/,
    actionKey: "payment.khqr.attempt.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/payments\/khqr\/confirm$/,
    actionKey: "payment.khqr.confirm",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/items\/all$/,
    actionKey: "menu.items.listAll",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/items\/[^/]+$/,
    actionKey: "menu.items.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items$/,
    actionKey: "menu.items.create",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/items\/[^/]+$/,
    actionKey: "menu.items.update",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items\/[^/]+\/archive$/,
    actionKey: "menu.items.archive",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items\/[^/]+\/restore$/,
    actionKey: "menu.items.restore",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PUT",
    pattern: /^\/menu\/items\/[^/]+\/visibility$/,
    actionKey: "menu.items.visibility.set",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/categories$/,
    actionKey: "menu.categories.list",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/categories$/,
    actionKey: "menu.categories.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/categories\/[^/]+$/,
    actionKey: "menu.categories.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/categories\/[^/]+\/archive$/,
    actionKey: "menu.categories.archive",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/menu\/modifier-groups$/,
    actionKey: "menu.modifierGroups.list",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups$/,
    actionKey: "menu.modifierGroups.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/modifier-groups\/[^/]+$/,
    actionKey: "menu.modifierGroups.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/archive$/,
    actionKey: "menu.modifierGroups.archive",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options$/,
    actionKey: "menu.modifierOptions.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options\/[^/]+$/,
    actionKey: "menu.modifierOptions.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options\/[^/]+\/archive$/,
    actionKey: "menu.modifierOptions.archive",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/modifier-groups\/[^/]+\/options\/[^/]+\/restore$/,
    actionKey: "menu.modifierOptions.restore",
    tenantSource: "token",
  },
  {
    method: "PUT",
    pattern: /^\/menu\/items\/[^/]+\/composition$/,
    actionKey: "menu.composition.upsert",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/menu\/items\/[^/]+\/composition\/evaluate$/,
    actionKey: "menu.composition.evaluate",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/discount\/rules$/,
    actionKey: "discount.rules.list",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/discount\/rules\/[^/]+$/,
    actionKey: "discount.rules.read",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/discount\/rules$/,
    actionKey: "discount.rules.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/discount\/rules\/[^/]+$/,
    actionKey: "discount.rules.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/discount\/rules\/[^/]+\/activate$/,
    actionKey: "discount.rules.activate",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/discount\/rules\/[^/]+\/deactivate$/,
    actionKey: "discount.rules.deactivate",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/discount\/rules\/[^/]+\/archive$/,
    actionKey: "discount.rules.archive",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/discount\/preflight\/eligible-items$/,
    actionKey: "discount.rules.preflight.eligibleItems",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/discount\/eligibility\/resolve$/,
    actionKey: "discount.eligibility.resolve",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/inventory\/categories$/,
    actionKey: "inventory.categories.list",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/categories$/,
    actionKey: "inventory.categories.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/inventory\/categories\/[^/]+$/,
    actionKey: "inventory.categories.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/categories\/[^/]+\/archive$/,
    actionKey: "inventory.categories.archive",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/inventory\/items$/,
    actionKey: "inventory.items.list",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/inventory\/items\/[^/]+$/,
    actionKey: "inventory.items.read",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/items$/,
    actionKey: "inventory.items.create",
    tenantSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/inventory\/items\/[^/]+$/,
    actionKey: "inventory.items.update",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/items\/[^/]+\/archive$/,
    actionKey: "inventory.items.archive",
    tenantSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/items\/[^/]+\/restore$/,
    actionKey: "inventory.items.restore",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/inventory\/restock-batches$/,
    actionKey: "inventory.restockBatches.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/restock-batches$/,
    actionKey: "inventory.restockBatches.create",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/inventory\/restock-batches\/[^/]+$/,
    actionKey: "inventory.restockBatches.updateMeta",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/restock-batches\/[^/]+\/archive$/,
    actionKey: "inventory.restockBatches.archive",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/inventory\/adjustments$/,
    actionKey: "inventory.adjustments.apply",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/inventory\/journal$/,
    actionKey: "inventory.journal.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/inventory\/stock\/branch$/,
    actionKey: "inventory.stock.branch.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/inventory\/stock\/aggregate$/,
    actionKey: "inventory.stock.aggregate.read",
    tenantSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/active$/,
    actionKey: "cashSession.active.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions$/,
    actionKey: "cashSession.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+$/,
    actionKey: "cashSession.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+\/movements$/,
    actionKey: "cashSession.movements.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+\/x$/,
    actionKey: "cashSession.x.view",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/cash\/sessions\/[^/]+\/z$/,
    actionKey: "cashSession.z.view",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions$/,
    actionKey: "cashSession.open",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/close$/,
    actionKey: "cashSession.close",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/force-close$/,
    actionKey: "cashSession.forceClose",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/movements\/paid-in$/,
    actionKey: "cashSession.movement.paidIn",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/movements\/paid-out$/,
    actionKey: "cashSession.movement.paidOut",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/cash\/sessions\/[^/]+\/movements\/adjustment$/,
    actionKey: "cashSession.movement.adjustment",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/checkout\/cash\/finalize$/,
    actionKey: "checkout.cash.finalize",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/checkout\/khqr\/initiate$/,
    actionKey: "checkout.khqr.initiate",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/checkout\/khqr\/intents\/[^/]+$/,
    actionKey: "checkout.khqr.intent.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/checkout\/khqr\/intents\/[^/]+\/cancel$/,
    actionKey: "checkout.khqr.intent.cancel",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/orders$/,
    actionKey: "order.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/orders\/[^/]+$/,
    actionKey: "order.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders$/,
    actionKey: "order.place",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders\/[^/]+\/cancel$/,
    actionKey: "order.cancel",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders\/[^/]+\/items$/,
    actionKey: "order.items.add",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/orders\/[^/]+\/checkout$/,
    actionKey: "order.checkout",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "PATCH",
    pattern: /^\/orders\/[^/]+\/fulfillment$/,
    actionKey: "order.fulfillment.status.update",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sales$/,
    actionKey: "sale.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sales\/[^/]+$/,
    actionKey: "sale.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/finalize$/,
    actionKey: "sale.finalize",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/request$/,
    actionKey: "sale.void.request",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/approve$/,
    actionKey: "sale.void.approve",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/reject$/,
    actionKey: "sale.void.reject",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sales\/[^/]+\/void\/execute$/,
    actionKey: "sale.void.execute",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sales\/[^/]+\/void-request$/,
    actionKey: "sale.void.request.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/receipts\/sales\/[^/]+$/,
    actionKey: "receipt.readBySale",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/receipts\/[^/]+$/,
    actionKey: "receipt.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/receipts\/[^/]+\/print$/,
    actionKey: "receipt.print",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/receipts\/[^/]+\/reprint$/,
    actionKey: "receipt.reprint",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/inbox$/,
    actionKey: "operationalNotification.inbox.list",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/unread-count$/,
    actionKey: "operationalNotification.inbox.unreadCount",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/stream$/,
    actionKey: "operationalNotification.inbox.stream",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/notifications\/[^/]+$/,
    actionKey: "operationalNotification.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/notifications\/[^/]+\/read$/,
    actionKey: "operationalNotification.read.mark",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/notifications\/read-all$/,
    actionKey: "operationalNotification.read.markAll",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sync\/replay$/,
    actionKey: "pushSync.apply",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sync\/push$/,
    actionKey: "pushSync.apply",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sync\/replay\/batches\/[^/]+$/,
    actionKey: "pushSync.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "GET",
    pattern: /^\/sync\/push\/batches\/[^/]+$/,
    actionKey: "pushSync.read",
    tenantSource: "token",
    branchSource: "token",
  },
  {
    method: "POST",
    pattern: /^\/sync\/pull$/,
    actionKey: "pullSync.pull",
    tenantSource: "token",
    branchSource: "token",
  },
];

export function matchProtectedRoute(
  method: string,
  path: string
): ProtectedRoute | null {
  return (
    PROTECTED_ROUTES.find(
      (candidate) => candidate.method === method && candidate.pattern.test(path)
    ) ?? null
  );
}
